### ISSUE TITLE
Question: SNGP initialization of random features

### ISSUE THREAD

**Issue by dhuseljic** [google/uncertainty-baselines#1217]
Hello, excellent work with this repository. 

I have a question regarding the initialization of random features. In the SNGP paper, you state that the random Fourier features' weight matrix is generated with a standard deviation of one. However, in this repository, you use a standard deviation of 0.05 for both ORF and RFF (on CIFAR).

How is this justified? Isn't that equivalent to setting the kernel scale to a high value, as the transformation into the Fourier space would look like this: cos(0.05·W h + b)? I may have missed something when going through the paper or code.

**Comment by jereliu** [comment]
Hi!

Thanks for this question! In some of our later work on much larger neural
networks and harder tasks (ResNet50 on ImageNet
<https://arxiv.org/abs/2205.00403> and ViT
<https://arxiv.org/abs/2207.07411>), we find out that it is important to
set the initialization variance of random feature layer to obtain
reasonable performance (a good rule of thumb is to set it to roughly
2/num_input_units, which corresponds to that used in He initialization
<https://github.com/google/edward2/blob/5338ae3244b90f3fdd0cf10094937c09eb40fab9/edward2/jax/nn/random_feature.py#L62>
).

As you said, this corresponds to adjusting the kernel length scale of the
RBF. Given that weight variance initialization is important for neural nets
(which can be understood as a version of kernel methods with learnable
kernel hyperparameters), and how important kernel length-scale tuning is
for GP performance, I do believe the careful setting of kernel length
scale to be important for GP on top of larger models and more difficult
problems.  This is something I think is overlooked in the classic random
feature literature (since it is often not used on top of deep nets).

**Comment by jereliu** [comment]
Hi!

Thanks for this question! In some of our later work on much larger neural
networks and harder tasks ([ResNet50 on ImageNet](https://arxiv.org/abs/2205.00403) and [ViT](https://arxiv.org/abs/2207.07411)), we find out that it is important to
set the initialization variance of random feature layer to obtain
reasonable performance (a good rule of thumb is to set it to roughly
2/num_input_units, which corresponds to that used in [He initialization](https://github.com/google/edward2/blob/5338ae3244b90f3fdd0cf10094937c09eb40fab9/edward2/jax/nn/random_feature.py#L62)).

As you said, this corresponds to adjusting the kernel length scale of the
RBF. Given that weight variance initialization is important for neural nets
(which can be understood as a version of kernel methods with learnable
kernel hyperparameters), and how important kernel length-scale tuning is
for GP performance, I do believe the careful setting of kernel length
scale to be important for GP on top of larger models and more difficult
problems.  This is something I think is overlooked in the classic random
feature literature (since it is often not used on top of deep nets).

**Comment by dhuseljic** [comment]
Thanks for this helpful answer!
