### ISSUE TITLE
Question about SNGP BERT flags

### ISSUE THREAD

**Issue by xuefei-wang** [google/uncertainty-baselines#1252]
Hi,

I noticed that for BERT_SNGP model, all of the below are implemented but the flags for the first two are set to False:
- 'spec_norm_att'
- 'spec_norm_ffn'
- 'spec_norm_plr'
Is there a particular reason for that? 

I also find it difficult to reconcile the implementation here with the official tensorflow tutorial (https://www.tensorflow.org/text/tutorials/uncertainty_quantification_with_sngp_bert) Which would be the better one to refer to?

Thanks!!

**Comment by jereliu** [comment]
Hi Xuefei!

If memory serves. They are set to False since they were found to be hurting
generalization on larger BERT models in preliminary experiments.

In general, please follow the official tutorial when working with smaller
models, and consider the setting tried here for larger models loaded from
pretrained checkpoints (eg BERT base or larger).

Thanks!
Jeremiah

**Comment by xuefei-wang** [comment]
Hi Jeremiah, that's very helpful, thanks! 
- Xuefei
