### ISSUE TITLE
Some appreciation and a question on evaluation

### ISSUE THREAD

**Issue by Jordy-VL** [google/uncertainty-baselines#255]
Yesterday I attended the _NeurIPS workshop on Practical Uncertainty Estimation and Out-of-Distribution Robustness in Deep Learning_, thanks for a great summary on recent advances, much appreciated! 
I have had a look around this referred repository and have some comments: 

(i) Love the repository!
(ii) How can I contribute? 
I am looking into benchmarking uncertainty methods for Named Entity Recognition, is this something you would like to include or would it be out-of-scope? 
(iii) Small question: you report ECE and Brier on the toxicity challenge, why not negative loglikelihood (log loss)? In general, proper scoring rules can be decomposed into calibration and refinement loss. I am wondering if Brier is not closer to ECE than log loss, which would be closer to accuracy? Is that the reason why you select Brier over log loss? 

Thank you very much!

Jordy Van Landeghem

**Comment by znado** [comment]
Hey! Sorry for the delay:

1. thanks so much :)
2. we'll gladly accept pull requests, preferably with a few of the existing methods in the codebase implemented on the new dataset (Deterministic, MIMO, SNGP, etc.)
3. I'll leave @jereliu to answer that!

**Comment by jereliu** [comment]
Hey Jordy,

2. Contribution welcome! If you are thinking about applying BERT-type model for NER task, feel free to use CLINC_INTENT benchmark as a template :)
3. In principle, log score and Brier score are equally preferable. For `toxic_comments`, we chose Brier because it is more commonly used in industrial practice, since it is easy to understand / interpret (nicely bounded between 0 and 1).

**Comment by jereliu** [comment]
Closing the issue now. Please feel free to re-open if needed.
